# 플레이어가 접속했을때 제보 갯수를 검색합니다.
join-check:
  enable: true
  # 몇개 이상부터 알림을 보낼지 설정합니다.
  condition: 1
  # 메시지를 설정합니다.
  message: "{player} 님의 제보 갯수: {count}"

# 일정 제보갯수가 넘는 유저를 차단합니다.
# 인터넷 연결상태가 좋지 않을시 접속이 지연될 수 있습니다.
ban:
  enable: true
  # 몇개 이상부터 차단할지 설정합니다.
  condition: 3
  # 차단 메시지를 설정합니다.
  ban-message: "당신은 우마공 DB의 제보 갯수가 3개 이상이기 때문에 차단되었습니다.{newline}더 자세한 정보는 https://userdb.ourmc.space/user/{uuid}"

# 메시지에 사용 가능한 플레이스홀더
# {player} - 플레이어 이름을 반환합니다.
# {count} - 플레이어의 제보 갯수를 반환합니다.
# {uuid} 플레이어의 UUID를 반환합니다. (- 가 없습니다)
# {newline} - 줄바꿈 문자를 반환합니다.